name: Deploy to UAT

on:
  push:
    branches: [uat]

jobs:
  dbt-deploy-uat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
<<<<<<< HEAD

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: pip install dbt-snowflake

      - run: dbt deps
        working-directory: mon_projet

      - run: dbt build --target uat
        working-directory: mon_projet
        env:
          DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
=======
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install dbt-snowflake
      - run: dbt deps
      - name: Create profiles.yml
        run: |
          mkdir -p ~/.dbt
          echo "mon_projet:" > ~/.dbt/profiles.yml
          echo "  target: uat" >> ~/.dbt/profiles.yml
          echo "  outputs:" >> ~/.dbt/profiles.yml
          echo "    uat:" >> ~/.dbt/profiles.yml
          echo "      type: snowflake" >> ~/.dbt/profiles.yml
          echo "      account: ${{ secrets.DBT_ACCOUNT }}" >> ~/.dbt/profiles.yml
          echo "      user: ${{ secrets.DBT_USER }}" >> ~/.dbt/profiles.yml
          echo "      password: \"${{ secrets.DBT_PASSWORD }}\"" >> ~/.dbt/profiles.yml
          echo "      role: ACCOUNTADMIN" >> ~/.dbt/profiles.yml
          echo "      database: DWH_REC" >> ~/.dbt/profiles.yml
          echo "      warehouse: DWH_REC" >> ~/.dbt/profiles.yml
          echo "      schema: PUBLIC" >> ~/.dbt/profiles.yml
          echo "      threads: 1" >> ~/.dbt/profiles.yml
      - run: dbt build --target uat
>>>>>>> uat
